name: depaware

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-go@v2
      with:
        go-version: '>=1.5 <2'

    - name: depaware
      run: go run github.com/tailscale/depaware -goos "linux,darwin,freebsd,openbsd,windows" -check bdd.fi/x/runitor/cmd/runitor
